TRAIN:
  ENABLE: True
  DATASET: diving48
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
#  CHECKPOINT_FILE_PATH: /home/matthew/Desktop/School/Research/SlowFast/checkpoints/model_zoo_pretrained/I3D_8x8_R50.pkl
#  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/matthew/Desktop/Datasets/Diving48
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.00375
  LR_POLICY: steps_with_relative_lrs
  LRS: [ 1, 0.1, 0.01, 0.001, 0.0001, 0.00001 ]
  STEPS: [ 0, 40, 60, 80, 100, 130 ]
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
#  BASE_LR: 0.1
#  LR_POLICY: cosine
#  MAX_EPOCH: 196
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-4
#  WARMUP_EPOCHS: 34.0
#  WARMUP_START_LR: 0.01
#  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 48
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: diving48
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: checkpoints/DEBUG_i3d_8x8_r50
WANDB_RUN_NAME: debug
