TRAIN:
  ENABLE: True
  DATASET: diving48
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
#  CHECKPOINT_FILE_PATH: /home/matthew/Desktop/School/Research/SlowFast/checkpoints/model_zoo_pretrained/SLOWFAST_8x8_R50.pkl
#  CHECKPOINT_TYPE: caffe2
  SHUFFLE_ONLY: False
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: /home/matthew/Desktop/Datasets/Diving48
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[2, 2], [2, 2], [2, 2], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: steps_with_relative_lrs
  LRS: [ 1, 0.1, 0.01, 0.001, 0.0001, 0.00001 ]
  STEPS: [ 0, 40, 60, 80, 100, 130 ]
  MAX_EPOCH: 150
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
#  BASE_LR: 0.1
#  LR_POLICY: cosine
#  MAX_EPOCH: 196
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-4
#  WARMUP_EPOCHS: 34.0
#  WARMUP_START_LR: 0.01
#  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 48
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: diving48
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
AUG:
  APP_DEBIAS: True
  APP_DEBIAS_WEIGHT: 1.0
  APP_DEBIAS_LOSS_FUNC: entropy
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: checkpoints/hloss_debug
WANDB_RUN_NAME: hloss_debug
