TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 1
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
#  CHECKPOINT_FILE_PATH: checkpoints/model_zoo_pretrained/SLOWFAST_8x8_R50.pkl
#  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: models/ar_models/checkpoints/fastonly_ssv2_4gpu_run1/checkpoints/checkpoint_epoch_00040.pyth
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: /home/matthew/Desktop/Datasets/ssv2/
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.03
  LR_POLICY: steps_with_relative_lrs
  LRS: [ 1, 0.1, 0.01, 0.001]
  STEPS: [ 0, 15, 30, 35]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
#  BASE_LR: 0.1
#  LR_POLICY: cosine
#  MAX_EPOCH: 196
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-4
#  WARMUP_EPOCHS: 34.0
#  WARMUP_START_LR: 0.01
#  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 174
  ARCH: slowfast
  MODEL_NAME: Fast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: ssv2
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: checkpoints/debug_f2
